language: generic

env:
  global:
    - TERRAFORM_VERSION=0.11.11
    - TERRAFORM_PATH=$HOME/bin

before_install:
  - wget "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" -O /tmp/terraform.zip

install:
  - unzip -d "${TERRAFORM_PATH}" /tmp/terraform.zip

before_script:
  - terraform init -input=false
  - terraform workspace select prd

script:
  - terraform validate
  - terraform fmt -check=true -diff
  - terraform plan -input=false -out=.terraform/tfplan

before_deploy:
  - terraform taint -allow-missing aws_api_gateway_base_path_mapping.main
  - terraform taint -allow-missing aws_api_gateway_deployment.main
  - terraform taint -allow-missing aws_lambda_function.index
  - terraform taint -allow-missing aws_lambda_function.about
  - terraform plan -input=false -out=.terraform/tfplan

deploy:
  skip_cleanup: true
  provider: script
  script:
    - terraform apply -input=false .terraform/tfplan
  on:
    branch: master
